using Bit_RPG.Char;

namespace Bit_RPG;

public partial class CharacterCreationPage : ContentPage
{
    // Add fields for UI controls if not auto-generated by XAML
    private Picker _classPicker;
    private Label _classDescription;
    private Picker _racePicker;
    private Label _raceDescription;
    private Entry _nameEntry;
    private RadioButton _maleRadio;
    private RadioButton _femaleRadio;

    public CharacterCreationPage()
    {
        InitializeComponent();

        // Initialize controls if not set by XAML
        _classPicker = this.FindByName<Picker>("ClassPicker");
        _classDescription = this.FindByName<Label>("ClassDescription");
        _racePicker = this.FindByName<Picker>("RacePicker");
        _raceDescription = this.FindByName<Label>("RaceDescription");
        _nameEntry = this.FindByName<Entry>("NameEntry");
        _maleRadio = this.FindByName<RadioButton>("MaleRadio");
        _femaleRadio = this.FindByName<RadioButton>("FemaleRadio");

        _classPicker.SelectedIndexChanged += OnClassPickerSelectedIndexChanged;
        _racePicker.SelectedIndexChanged += OnRacePickerSelectedIndexChanged;
    }

    private void OnRacePickerSelectedIndexChanged(object sender, EventArgs e)
    {
        // Update race description based on selection
        switch (_racePicker.SelectedIndex)
        {
            case 0: // Human
                _raceDescription.Text = "Balanced and versatile, humans excel in all areas with no particular weaknesses.";
                break;
            case 1: // Elf
                _raceDescription.Text = "Agile and intelligent, elves are naturally gifted in magic and possess keen senses.";
                break;
            case 2: // Dwarf
                _raceDescription.Text = "Strong and resilient, dwarves are excellent warriors with high defense and health.";
                break;
        }
    }

    private void OnClassPickerSelectedIndexChanged(object sender, EventArgs e)
    {
        // Update class description based on selection
        switch (_classPicker.SelectedIndex)
        {
            case 0: // Warrior
                _classDescription.Text = "A strong and resilient fighter, excelling in melee combat and heavy armor.";
                break;
            case 1: // Mage
                _classDescription.Text = "A master of arcane arts, wielding powerful spells to devastate enemies from afar.";
                break;
            case 2: // Rogue
                _classDescription.Text = "A stealthy and agile character, skilled in sneaking, lockpicking, and critical strikes.";
                break;
        }
    }

    private async void OnStartAdventureClicked(object sender, EventArgs e)
    {
        // Validate inputs
        if (string.IsNullOrWhiteSpace(_nameEntry.Text))
        {
            await DisplayAlert("Error", "Please enter a character name", "OK");
            return;
        }

        if (_racePicker.SelectedIndex == -1)
        {
            await DisplayAlert("Error", "Please select a race", "OK");
            return;
        }

        if (_classPicker.SelectedIndex == -1)
        {
            await DisplayAlert("Error", "Please select a class", "OK");
            return;
        }

        // Create player
        Player player = new Player
        {
            PlayerName = _nameEntry.Text,
            Age = 16,
            Male = _maleRadio.IsChecked,
            Female = _femaleRadio.IsChecked,
            Pronouns = _maleRadio.IsChecked ? "he/him" : "she/her"
        };

        // Apply race
        switch (_racePicker.SelectedIndex)
        {
            case 0:
                player.Race = RaceType.Human;
                break;
            case 1:
                player.Race = RaceType.Elf;
                break;
            case 2:
                player.Race = RaceType.Dwarf;
                break;
        }

        // Apply class
        switch (_classPicker.SelectedIndex)
        {
            case 0:
                player.Class = ClassType.Warrior;
                PlayerClass.Warrior(player);
                break;
            case 1:
                player.Class = ClassType.Mage;
                PlayerClass.Mage(player);
                break;
            case 2:
                player.Class = ClassType.Rogue;
                PlayerClass.Rogue(player);
                break;
        }

        // Apply race bonuses
        switch (player.Race)
        {
            case RaceType.Human:
                PlayableRaces.Human(player);
                break;
            case RaceType.Elf:
                PlayableRaces.Elf(player);
                break;
            case RaceType.Dwarf:
                PlayableRaces.Dwarf(player);
                break;
        }

        // Navigate to game page with player data
        await Navigation.PushAsync(new GamePage(player));
    }
}