using Bit_RPG.Char;

namespace Bit_RPG;

public partial class CharacterCreationPage : ContentPage
{
    // Add fields for UI controls if not auto-generated by XAML
    private Picker _classPicker;
    private Label _classDescription;
    private Entry _nameEntry;
    private RadioButton _maleRadio;
    private RadioButton _femaleRadio;

    public CharacterCreationPage()
    {
        InitializeComponent();

        // Initialize controls if not set by XAML
        _classPicker = this.FindByName<Picker>("ClassPicker");
        _classDescription = this.FindByName<Label>("ClassDescription");
        _nameEntry = this.FindByName<Entry>("NameEntry");
        _maleRadio = this.FindByName<RadioButton>("MaleRadio");
        _femaleRadio = this.FindByName<RadioButton>("FemaleRadio");

        _classPicker.SelectedIndexChanged += OnClassPickerSelectedIndexChanged;
    }

    private void OnClassPickerSelectedIndexChanged(object sender, EventArgs e)
    {
        // Update class description based on selection
        switch (_classPicker.SelectedIndex)
        {
            case 0: // Warrior
                _classDescription.Text = "A strong and resilient fighter, excelling in melee combat and heavy armor.";
                break;
            case 1: // Mage
                _classDescription.Text = "A master of arcane arts, wielding powerful spells to devastate enemies from afar.";
                break;
            case 2: // Rogue
                _classDescription.Text = "A stealthy and agile character, skilled in sneaking, lockpicking, and critical strikes.";
                break;
        }
    }

    private async void OnStartAdventureClicked(object sender, EventArgs e)
    {
        // Validate inputs
        if (string.IsNullOrWhiteSpace(_nameEntry.Text))
        {
            await DisplayAlert("Error", "Please enter a character name", "OK");
            return;
        }

        if (_classPicker.SelectedIndex == -1)
        {
            await DisplayAlert("Error", "Please select a class", "OK");
            return;
        }

        // Create player
        Player player = new Player
        {
            PlayerName = _nameEntry.Text,
            Male = _maleRadio.IsChecked,
            Female = _femaleRadio.IsChecked,
            Pronouns = _maleRadio.IsChecked ? "he/him" : "she/her"
        };

        // Apply class
        switch (_classPicker.SelectedIndex)
        {
            case 0:
                PlayerClass.Warrior(player);
                break;
            case 1:
                PlayerClass.Mage(player);
                break;
            case 2:
                PlayerClass.Rogue(player);
                break;
        }

        // Navigate to game page with player data
        await Navigation.PushAsync(new GamePage(player));
    }
}